# ====================
# CLIENTS
# ====================

### Get Clients
GET http://localhost:3000/api/clients


### Get Client By ID
GET http://localhost:3000/api/clients/1


### Post Client
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "firstName": "Pepite",

    "phone": "3209419317"
}


### Put Client
PUT http://localhost:3000/api/clients/9
Content-Type: application/json

{
    "firstName": "Pepita",
    "lastName": "Perez",
    "phone": "3111111111"
}

### Delete Client
DELETE http://localhost:3000/api/clients/6


# ====================
# Admins
# ====================

### Login Admins
POST http://localhost:3000/api/admins
Content-Type: application/json

{
    "username": "admin",
    "passwordHash": "admin123"
}


# ====================
# Employees
# ====================

### Get Employees
GET http://localhost:3000/api/employees


### Get Employee By ID
GET http://localhost:3000/api/employees/11


### Get Employees By Service
GET http://localhost:3000/api/employees/service/1


### Get Employee Schedule
GET http://localhost:3000/api/employees/schedule/1


### Post Employee
POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "firstName": "Fulano",
    "lastName": "Tal",
    "phone": "3000000000",
    "salary": 2000000,
    "startTime": "08:00:00",
    "endTime": "18:00:00",
    "hireDate": "2026-05-31"
}


### Put Employee
PUT http://localhost:3000/api/employees/6
Content-Type: application/json

{
    
    "firstName": "Fulano",
    "lastName": "Tal",
    "phone": "3000000001",
    "salary": 2000000,
    "startTime": "08:00:00",
    "endTime": "18:00:00",
    "hireDate": "2026-05-31"
}

### Delete Employee
DELETE http://localhost:3000/api/employees/6


# ====================
# Service
# ====================

### Get Services
GET http://localhost:3000/api/services


### Get Service By ID
GET http://localhost:3000/api/services/7


### Post Service
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Corte clásico",
    "description": "Corte tradicional para caballero",
    "imageUrl": "corte.png",
    "durationMinutes": 30,
    "basePrice": 15000
}


### Put Service
PUT http://localhost:3000/api/services/4
Content-Type: application/json

{
    "name": "Corte premium",
    "description": "Incluye lavado",
    "imageUrl": "premium.png",
    "durationMinutes": 45,
    "basePrice": 25000
}


### Delete Service
DELETE http://localhost:3000/api/services/4


# ====================
# EMPLOYEESERVICE
# ====================

### Get Relations
GET http://localhost:3000/api/EmployeeService


### Get Relation By ID
GET http://localhost:3000/api/EmployeeService/1


### Assign Service To Employee
POST http://localhost:3000/api/EmployeeService
Content-Type: application/json

{
    "employeeid": 5,
    "serviceid": 3
}


### Update Relation
PUT http://localhost:3000/api/EmployeeService/8
Content-Type: application/json

{
    "employeeid": 5,
    "serviceid": 1
}


### Delete Relation
DELETE http://localhost:3000/api/EmployeeService/13


# ====================
# Appointments
# ====================

### Get Appointments
GET http://localhost:3000/api/appointments


### Get Appointments By Client
GET http://localhost:3000/api/appointments/client/1


### Get Appointment By ID
GET http://localhost:3000/api/appointments/1


### Get Available Hours
GET http://localhost:3000/api/appointments/available-hours/1/2026-06-17


### Create Appointment
POST http://localhost:3000/api/appointments
Content-Type: application/json

{
    "appointmentDate": "2026-06-07 14:30:00",
    "clientid": 1,
    "employeeid": 1,
    "serviceid": 1
}


### Update Appointment
PUT http://localhost:3000/api/appointments/1
Content-Type: application/json

{
    "appointmentDate": "2026-06-07 15:00:00",
    "finalPrice": 30000,
    "clientid": 1,
    "employeeid": 1,
    "serviceid": 2
}


### Update Appointment Status
PUT http://localhost:3000/api/appointments/status/1
Content-Type: application/json

{
    "status": "Cancelled"
}


### Delete Appointment
DELETE http://localhost:3000/api/appointments/1


# ====================
# AUTH
# ====================

### Register Client
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName": "Angela",
    "lastName": "Rodriguez",
    "phone": "3001234569",
    "passwordHash": "1234"
}


### Login Client
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "phone": "3001234568",
    "passwordHash": "1234"
}